# Generated by Django 3.2.5 on 2021-07-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210727_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('Motocicleta', 'Motocicleta'), ('Triciclo', 'Triciclo'), ('Quadriciclo', 'Quadriciclo'), ('Carro', 'Carro'), ('Microônibus', 'Microônibus'), ('Ônibus', 'Ônibus'), ('Reboque', 'Reboque'), ('Caminhonete', 'Caminhonete'), ('Caminhão', 'Caminhão'), ('Trator', 'Trator')], default='Carro', max_length=16),
        ),
    ]
