# Generated by Django 3.2.5 on 2021-07-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210727_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cilindrada',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Motocicleta', 'Motocicleta'), ('Caminhonete', 'Caminhonete'), ('Caminhão', 'Caminhão'), ('Ônibus', 'Ônibus'), ('Microônibus', 'Microônibus'), ('Triciclo', 'Triciclo'), ('Quadriciclo', 'Quadriciclo'), ('Reboque', 'Reboque'), ('Trator', 'Trator')], default='Carro', max_length=16),
        ),
    ]
